title: HTTPlug
email: team@httplug.io
description: HTTPlug, the HTTP client abstraction for PHP.
baseurl: ""
url: "http://httplug.io"
twitter_username: httplug
github_username: php-http
github_reponame: httplug
exclude: [vendor]

sass:
  sass_dir: assets/_sass
  style: compressed

# Build settings
markdown: kramdown

gems:
  - jekyll-mentions
