title: HTTPlug
email: team@httplug.io
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://httplug.io"
twitter_username: httplug
github_username:  php-http

# Build settings
markdown: kramdown
